log:
  level: DEBUG
  filepath: "/etc/traefik/log/traefik.log"
api:
  dashboard: true
entryPoints:
  insecure:
    address: ":80"
  secure:
    address: ":443"
  login:
    address: ":6900"
  map: 
    address: ":5121"
  char:
    address: ":6121"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_config.yml"
    watch: true
certificatesResolvers:
  le:
    acme:
      email: bryan@avalonstar.com
      storage: /acme.json
      httpChallenge:
        entryPoint: insecure