api:
  dashboard: true

entryPoints:
  insecure:
    address: ":80"
  secure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: landale.app
            sans:
                - "*.landale.app"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "104.60.90.194/32"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_config.yml"
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: bryan@avalonstar.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  http:
    acme:
      email: bryan@avalonstar.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: insecure

log:
  level: DEBUG
  filePath: "/logs/traefik.log"
  format: json

accesslog:
  filePath: "/logs/access.log"
  bufferingsize: 5000
  format: json
  filters:
    statusCodes:
      - "400-499"
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        CF-Connecting-IP: keep
