name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .production.env
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .production.env
          echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .production.env
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .production.env
          echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> .production.env
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '14'
      - name: Setup shared network
        run: docker network create traefik-network
      - name: Build the stack
        run: docker-compose up -d
